# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

pr: none

pool:
  vmImage: windows-latest

steps:
# Copy AzureDeploy Files To Staging Directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\TempController.DotNet'
    Contents: '**\AzureDeploy\**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# Copy Script Files To Staging Directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)\TempController.DotNet'
    Contents: '**\Scripts\**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)\Scripts'
    flattenFolders: true

# Publish Artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'TempControllerArtifact'